-- CreateTable
CREATE TABLE `Role` (
    `id` VARCHAR(191) NOT NULL,
    `name` ENUM('PATIENT', 'AYURVEDA_DOCTOR', 'BDS_DOCTOR', 'ALLOPATHY_DOCTOR', 'SIDDHA_SPECIALIST', 'HOMEOPATHY_SPECIALIST', 'UNANI_SPECIALIST', 'HOSPITAL_ADMIN', 'DISTRICT_OFFICER', 'NATIONAL_ADMIN', 'PHARMACIST', 'STATE_OFFICER') NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `Role_name_key`(`name`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `User` (
    `id` VARCHAR(191) NOT NULL,
    `email` VARCHAR(191) NOT NULL,
    `passwordHash` VARCHAR(191) NOT NULL,
    `roleId` VARCHAR(191) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `User_email_key`(`email`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `ADRReport` (
    `id` VARCHAR(191) NOT NULL,
    `userId` VARCHAR(191) NOT NULL,
    `medicineName` VARCHAR(191) NOT NULL,
    `category` ENUM('AYURVEDA', 'SIDDHA', 'UNANI', 'HOMEOPATHY', 'ALLOPATHY', 'BDS_DENTAL') NOT NULL,
    `symptoms` VARCHAR(500) NOT NULL,
    `severity` ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL') NOT NULL,
    `status` ENUM('PENDING', 'AI_REVIEWED', 'APPROVED', 'REJECTED', 'ESCALATED', 'FORWARDED_TO_PHARMACIST', 'REJECTED_BY_PHARMACIST', 'FORWARDED_TO_DISTRICT', 'REJECTED_BY_DISTRICT', 'FORWARDED_TO_STATE_PVPI', 'APPROVED_BY_STATE') NOT NULL DEFAULT 'PENDING',
    `manufacturer` VARCHAR(191) NULL,
    `batchNumber` VARCHAR(191) NULL,
    `pharmacistComment` VARCHAR(500) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `User` ADD CONSTRAINT `User_roleId_fkey` FOREIGN KEY (`roleId`) REFERENCES `Role`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `ADRReport` ADD CONSTRAINT `ADRReport_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
